name: Deploy CI

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.DENO_DEPLOY_PROJECT }}
          entrypoint: src/index.ts